services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
    ports:
      - "5432:5432"
    # volumes:
    #   - data:/var/lib/postgresql/data

  mailcatcher:
    image: dockage/mailcatcher
    restart: always
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  data:
